# Generated by Django 3.1 on 2020-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click link above to read blog post.....', max_length=255),
        ),
    ]
